### ISSUE TITLE
Create chapter workflow

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/proudlyserving.github.io#16]
## Workflow

[Chapter workflow checklist doc](https://docs.google.com/document/d/1uka6vVsdEPu5jiqEM_oG0yrkACYj7ARPabyxHbRkkwc/edit?usp=sharing)

## To-do

- [x] Create doc, add to issue
- [x] Finalize workflow
- [x] Turn checklist into issue template

**Comment by rebeccawoodbury** [comment]
@lukefretwell this looks great, and comprehensive!

**Comment by rebeccawoodbury** [comment]
doc created, assigned roles, added some steps

**Comment by lukefretwell** [comment]
@rebeccawoodbury added to doc but this is what the issue will look like (select 'Preview'):

https://github.com/proudlyserving/book/issues/new?assignees=lukefretwell%2C+rebeccawoodbury&labels=content&template=new-chapter.md&title=Chapter%3A+%5BTITLE%5D

**Comment by rebeccawoodbury** [comment]
@lukefretwell issue template updated with maintainer roles

**Comment by lukefretwell** [comment]
@rebeccawoodbury I made some minor modifications, but it's now ready to test! 🚀

**Comment by rebeccawoodbury** [comment]
@lukefretwell @Marlena-Medford reopening to add Marlena to this

**Comment by rebeccawoodbury** [comment]
@lukefretwell @Marlena-Medford I added a couple of items to the workflow doc for scheduling and having the kick-off meeting

**Comment by rebeccawoodbury** [comment]
@lukefretwell @Marlena-Medford reminder that we want to add a timeframe for writing a chapter. this timeline should be added to the workflow and ops templates. thoughts on how long this should be? how does one month sound?

**Comment by lukefretwell** [comment]
@rebeccawoodbury @Marlena-Medford see my comments in the doc. I think we should definitely incorporate into the workflow. I think around six weeks for the whole process is realistic, especially given we've created a framework.

https://docs.google.com/document/d/1uka6vVsdEPu5jiqEM_oG0yrkACYj7ARPabyxHbRkkwc/edit?usp=sharing

**Comment by lukefretwell** [comment]
@rebeccawoodbury I added updates to the issue template (+ @Marlena-Medford to the issue as an assignee):

https://github.com/proudlyserving/book/issues/new?assignees=lukefretwell%2C+rebeccawoodbury&labels=content&template=new-chapter.md&title=Chapter%3A+%5BTITLE%5D

One thing we should think about is when @Marlena-Medford is plugged into this. The more specific we can be the more clarity we'll all have, so @Marlena-Medford just let us know what works best for you.
