### ISSUE TITLE
Create working doc template for each chapter

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/proudlyserving.github.io#17]
[Chapter template](https://docs.google.com/document/d/1F4-q5iwiiJgs8aVbEllfrWzO9v7hLQSCgCBpQmFnGNU/edit?usp=sharing)

**Comment by rebeccawoodbury** [comment]
Template created. Moving back to To Do until we have chapter titles.

**Comment by lukefretwell** [comment]
@rebeccawoodbury this is great. I think this issue is done and we need to fold the template into the workflow. Do we want to include instructions in the doc, such as word count, recommendations, format, link to style guide? Seems like it would be easier for contributors to just work from the document and have all of that in one place.

**Comment by rebeccawoodbury** [comment]
@lukefretwell agree, I like the idea of including instructions in the doc. Added a section to the doc.
