### ISSUE TITLE
Create working doc for manuscript

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/proudlyserving.github.io#22]
- [x] create separate doc for extraneous ideas
- [x] move content out of manuscript into new doc

**Comment by rebeccawoodbury** [comment]
- [Working doc](https://docs.google.com/document/d/1gKXFCvitMR1OUZlazhDAdC8DHm72dY973DA_q652feY/edit#)
- [Manuscript](https://docs.google.com/document/d/1oWuhH1d02Z0IxaDAdcFBp7wZUaoFtwn9VBLxEXAjDgg/edit#)
