### ISSUE TITLE
Invite collaborators

### ISSUE THREAD

**Issue by rebeccawoodbury** [proudlyserving/proudlyserving.github.io#24]
- [x] identify subject matter experts ([spreadsheet](https://docs.google.com/spreadsheets/d/1jLI9bZEjcSEAcQxqwuakloer9IEyPZXUVkVeDhUooRA/edit?usp=sharing))
- [x] invite people
- [x] reach out to key Slack groups

**Comment by lukefretwell** [comment]
@rebeccawoodbury let's figure out how best to incorporate this into our check-ins. Would be great to pick off chapters in the backlog for specific people or to promote one each week.
