### ISSUE TITLE
Create style guide

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/proudlyserving.github.io#38]
- [x] Add /style page
- [x] Add link to footer
- [x] Design (@lukefretwell)
- [x] Editorial (@rebeccawoodbury)

**Comment by lukefretwell** [comment]
@rebeccawoodbury you want to handle the editorial part? 

https://proudlyservingbook.com/style/

**Comment by rebeccawoodbury** [comment]
@lukefretwell started a draft editorial style guide in the [working doc](https://docs.google.com/document/d/1gKXFCvitMR1OUZlazhDAdC8DHm72dY973DA_q652feY/edit#heading=h.ysqn7uuypurd). thoughts?
