### ISSUE TITLE
Call to action

### ISSUE THREAD

**Issue by rebeccawoodbury** [proudlyserving/proudlyserving.github.io#39]
- [x] Publish

**Comment by lukefretwell** [comment]
@Marlena-Medford @rebeccawoodbury ready for feedback:

https://docs.google.com/document/d/1XIKUIo4V4n1d79EAAinsuEDxuYfIf6HMLsUReNLjuZo/edit?usp=sharing

**Comment by lukefretwell** [comment]
Done: https://proudlyservingbook.com/download/
