### ISSUE TITLE
Set up Linkedin

### ISSUE THREAD

**Issue by rebeccawoodbury** [proudlyserving/proudlyserving.github.io#40]
- [x] Create page
- [x] Customize profile
- [x] Make @rebeccawoodbury @lukefretwell admins
- [x] Add icon to footer
- [x] Add to manuscript/website where appropriate
- [x] Add 'Maintainer' to LI profiles

**Comment by lukefretwell** [comment]
FYI @rebeccawoodbury: https://www.linkedin.com/company/proudlyserving

**Comment by rebeccawoodbury** [comment]
@lukefretwell added to manuscript, closing issue
