### ISSUE TITLE
Hello world blog post

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/proudlyserving.github.io#42]

**Comment by lukefretwell** [comment]
@rebeccawoodbury think we can do something simple here just to fill in the feeds and test.

**Comment by rebeccawoodbury** [comment]
[Draft Hello World post](https://docs.google.com/document/d/1mz7RInCfZoAhrnnuyi-Q5GESPY5IbUR5u9Dkn6ENAfI/edit?usp=sharing)

Thoughts @lukefretwell ?

**Comment by lukefretwell** [comment]
@rebeccawoodbury 👋 💥 

https://proudlyservingbook.com/welcome-to-proudly-serving/
