### ISSUE TITLE
Set up folder/docs in PS account

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/proudlyserving.github.io#43]
- [x] Set up Drive on Proudly Serving
- [x] Move documents to Proudly Serving Drive
- [x] Set up document template styles
- [x] Set up permissions
- [x] [Delete folder/files](https://drive.google.com/drive/folders/1G1I456e5pWUkqiC-Kxcu3eEm_G7Bn9Nk?usp=sharing) @rebeccawoodbury

**Comment by lukefretwell** [comment]
@rebeccawoodbury I just want to make sure we have everything in the PS Google account. Also, want to make sure we're starting docs from there and that they have the right styles. Looks like the hello world post is using a combo of PS and DoCT styles.

**Comment by lukefretwell** [comment]
@rebeccawoodbury if you could verify the first two, I can take care of the third.

**Comment by lukefretwell** [comment]
@rebeccawoodbury updated with just one checklist item for you to address.

**Comment by rebeccawoodbury** [comment]
@lukefretwell in the doc styles, H2 and H3 look really similar in size. Should we make H3 a bit smaller?

**Comment by lukefretwell** [comment]
@rebeccawoodbury I modified the styles and reset for the docs we have.
