### ISSUE TITLE
Create email/social templates

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/proudlyserving.github.io#44]
To streamline the communications (with contributors + community) let's create templates for the following:

[Doc](https://docs.google.com/document/d/1JzJrG2J7WzbtGK-A3TgSVCkyXHJJFuqriVn_vIxTj-8/edit#heading=h.1yfb0xjocjrm)

- [x] Blog post (feedback / published)
- [x] Social media (feedback / published)
- [x] Emails (contributor welcome - how to get started + contributor feedback - share with community + contributor publish - share 'final' chapter / thank you)
- [x] Create Gmail templates

**Comment by lukefretwell** [comment]
@rebeccawoodbury I created an ops doc and a section there for these. You'll see I also create template docs for the posts which are linked in ops doc.

Could you take lead on this?

**Comment by rebeccawoodbury** [comment]
[Email templates started in this doc](https://docs.google.com/document/d/19gzaJusYc7aRhE_uYR1FGmp39o27SyyganUwaSQMjDQ/edit?usp=sharing)

**Comment by rebeccawoodbury** [comment]
[Social media templates started in this doc](https://docs.google.com/document/d/1ae3KhtUHWs_T7zHWb7ZjuIR7i4O-KTMxzHjaA_XIrvM/edit?usp=sharing)

**Comment by rebeccawoodbury** [comment]
@lukefretwell last outstanding question on this is if we want to set a timeframe for feedback. thoughts?
