### ISSUE TITLE
Set up a calendly account

### ISSUE THREAD

**Issue by rebeccawoodbury** [proudlyserving/proudlyserving.github.io#46]
- [x] create account
- [x] customize
- [x] Add three morning time blocks
- [x] Add link to welcome email
- [x] Integrate Zoom (set up PS Zoom account)
- [x] Test the scheduler

**Comment by rebeccawoodbury** [comment]
@lukefretwell there's a Zoom integration. Should we use ProudCity's zoom account or mine? Or set up a free account for Proudly Serving?

**Comment by lukefretwell** [comment]
@rebeccawoodbury done with customizing.

[These workflows](https://calendly.com/app/workflows/user/me) might be helpful to set up. I add the 24-hour prior automated reminder one.

**Comment by lukefretwell** [comment]
@rebeccawoodbury disregard workflow comment. Just seeing that it's a 14-day trial.
