### ISSUE TITLE
QA PS

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/proudlyserving.github.io#50]
Review:

- [ ] [Style guide](https://proudlyservingbook.com/style/)
- [ ] For style guide, add reference to vendors/products
- [ ] [Website](https://proudlyservingbook.com/)
- [ ] [Workflow](https://docs.google.com/document/d/1uka6vVsdEPu5jiqEM_oG0yrkACYj7ARPabyxHbRkkwc/edit?usp=sharing)
- [ ] [Ops doc](https://docs.google.com/document/d/1JzJrG2J7WzbtGK-A3TgSVCkyXHJJFuqriVn_vIxTj-8/edit?usp=sharing)
- [ ] Add quotes around "Proudly Serving" on website, etc.

**Comment by rebeccawoodbury** [comment]
@Marlena-Medford for style guide, can you add an item about vendors not using this as a marketing tool?

**Comment by lukefretwell** [comment]
@Marlena-Medford @rebeccawoodbury I added a checklist item above.

**Comment by lukefretwell** [comment]
@Marlena-Medford closing this out.

Notes:

* No quotes on Proudly Serving
* @Marlena-Medford can you flag anything that you edited that needs to be changed elsewhere?
