### ISSUE TITLE
QA form confirmations

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/proudlyserving.github.io#51]

**Comment by rebeccawoodbury** [comment]
@lukefretwell I can't figure this one out. Maybe Kevin knows?

**Comment by lukefretwell** [comment]
@rebeccawoodbury is it both forms?

**Comment by rebeccawoodbury** [comment]
@lukefretwell I think it's just the contributor interest form

**Comment by lukefretwell** [comment]
@rebeccawoodbury well, can you verify? 😛

**Comment by lukefretwell** [comment]
@rebeccawoodbury sounds like we need to set up the SMTP, so I'm just just disabling those for now.
